### ISSUE TITLE
Twitch.tv Auth problem erroer

### ISSUE THREAD

**Issue by dimtoneff** [mirror/jdownloader#15]
Hello, getting the error when trying to enable twitch account auth:

------------------------Thread: 106:accountCheck:twitch.tv_jd.plugins.hoster.TwitchTv-----------------------
--ID:106TS:1555273575980-4/14/19 10:26:15 PM -  [] -> Exception thrown at jd.plugins.PluginForHost.handleAccountException(PluginForHost.java:249):
jd.plugins.PluginException: ERROR_PLUGIN_DEFECT|Value:-1
	at jd.plugins.hoster.TwitchTv.login(TwitchTv.java:647)
	at jd.plugins.hoster.TwitchTv.fetchAccountInfo(TwitchTv.java:711)
	at jd.controlling.AccountController.updateAccountInfo(AccountController.java:323)
	at jd.controlling.accountchecker.AccountChecker$AccountCheckJob.check(AccountChecker.java:47)
	at jd.controlling.accountchecker.AccountChecker$1.run(AccountChecker.java:155)

https://github.com/mirror/jdownloader/blob/b76e1e61da3d2d8e167c471f9630022c213d9363/src/jd/plugins/hoster/TwitchTv.java#L647

**Comment by majuss** [comment]
https://github.com/streamlink/streamlink/issues/2680

Look at this thread, the unofficial twitch third party api is offline at random moments.
